# Generated by Django 4.0.2 on 2022-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/media', verbose_name='Author Profile Image'),
        ),
    ]
